### ISSUE TITLE
Remove `text_type.ANSWER` from `There is no country better than {your country}.` message

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#103]
If you type unavailable numbers to script you can see message `There is no country better than {your country}.`
But right now you can see this message and text `text_type.ANSWER`
`text_type.ANSWER` need to remove.
Thank you very much.
![Screenshot from 2019-10-04 23-31-03](https://user-images.githubusercontent.com/24910277/66238099-6fe77700-e6ff-11e9-929c-b97c95bec824.png)

**Comment by molnarjani** [comment]
Hi,
picking this up :)

**Comment by molnarjani** [comment]
PR: https://github.com/serhii73/place2live/pull/104

Travis seems to be failing, but i'm not sure if it's supposed to be working, this prehook is failing: https://github.com/asottile/add-trailing-comma
Build: https://travis-ci.org/serhii73/place2live/builds/593738931?utm_source=github_status&utm_medium=notification

**Comment by serhii73** [comment]
Thank you very much!
Can you please fix Travis's error?

**Comment by yonash2** [comment]
I can try to have a deeper look, but TBH i have 0 experience with Travis.
Will give it a try tomorrow :)

**Comment by serhii73** [comment]
Thank you very much!

**Comment by gunjanraval** [comment]
@yonash2 @molnarjani add a comma ',' at line 403 after the parenthesis to pass the test

**Comment by molnarjani** [comment]
thanks @gunjanraval, indeed that solved it :)
