### ISSUE TITLE
Remove travis from the project

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#109]
This project will be using [github actions](https://github.com/features/actions) instead of Travis.
Can you please remove Travis from this project?
1. Remove travis config
2. Remove travis icon from the readme
3. Remove TravisBuddy

**Comment by cartucciam** [comment]
Okay, I can do this :)

**Comment by serhii73** [comment]
Sorry @cartucciam, @CherryKitten was faster.
@CherryKitten Thank you very much for your PR.
@cartucciam you can take other issues in this repo.
Thank you very much!
