### ISSUE TITLE
Add Dockerfile to the project

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#122]
I want to add Docker to this project.
Right now need to install python, libraries and then run `python where.py`
I want to facilitate launching with Docker.

**Comment by markeyev** [comment]
Hello @serhii73,
I think I can do this. Could you please clarify, you need Docker for local debugging purpose or for example for running it in GCP App Engine Flexible Environment?

**Comment by kudoabhijeet** [comment]
Hey, I would like to contribute.

**Comment by serhii73** [comment]
@markeyev @kudoabhijeet 
Hello, guys. How are you?
Thank you for interesting in this issue.
Sorry but I have a PR for this issue but I have a problem when I run the script with Docker.
Can you help me?
https://github.com/serhii73/place2live/pull/123
Thank you very much!
