### ISSUE TITLE
Create a logo for the project

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#125]
Can you please create and add a logo for this project?

**Comment by MisaelSantos** [comment]
![favicon](https://user-images.githubusercontent.com/44177887/66406615-49a52e00-e9c2-11e9-945a-41a41c82c5b5.png)

**Comment by viyanateaa** [comment]
https://github.com/serhii73/place2live/pull/127

**Comment by xavierrollet** [comment]
https://github.com/xavierrollet/place2live/tree/master/logo

I suggested a logo
![logo](https://user-images.githubusercontent.com/56123802/66420234-d1605c00-ea05-11e9-85dd-a7f59e4eae6a.png)

**Comment by ShobhitRathi** [comment]
ill also try

**Comment by perun-01** [comment]
is it still open??.if it is, then I could create something better though..

**Comment by serhii73** [comment]
> is it still open??.if it is, then I could create something better though..

It will be awesome.
Thank you very much!
