### ISSUE TITLE
Add instruction to reorder imports

### ISSUE THREAD

**Issue by tandelDipak** [serhii73/place2live#144]
Most of the time people will send pull request without reordering imports. Hence, again and again, you have to explain them. So, it's better to add instruction in contributing.md file.

**Comment by tandelDipak** [comment]
@serhii73 I have added the instruction in contributing.md file. If you allow me I will send a pull request. I have also referred to contributing.md file in README.md file, so most of the people will check it while reading README.md.

**Comment by serhii73** [comment]
It's brilliant.
```
pip install pre-commit
pre-commit install
pre-commit run --all-files
```
It's can help for development.
