### ISSUE TITLE
Add info to where.py

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#148]
https://github.com/place2live/place2live/blob/master/english_speaking_population/EnglishSpeakingPopulation.csv this data to where.py output?
![Screenshot from 2019-10-10 08-49-49](https://user-images.githubusercontent.com/24910277/66677790-19d08180-ec73-11e9-81c2-ac9be0ac0674.png)
You can add a new column and add this information, is it ok?
Thank you very much!

_Originally posted by @serhii73 in https://github.com/place2live/place2live/issues/142#issuecomment-541187179_

**Comment by dgupta04** [comment]
Can I work on this?

**Comment by dgupta04** [comment]
The file https://github.com/place2live/place2live/blob/master/city/output/list_of_countries.csv does not have the column for English Speaking Population, shall I make a separate Pandas dataframe for it?

**Comment by serhii73** [comment]
You need to add to the ready data frame a new column with this [data](https://github.com/place2live/place2live/blob/master/english_speaking_population/EnglishSpeakingPopulation.csv).
Does that make sense?
Thank you very much!

**Comment by AmbiTyga** [comment]
May I work on this?
