### ISSUE TITLE
Add world justice information to where.py

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#160]
https://github.com/place2live/place2live/blob/master/world_justice_project/world_justice.csv
Can you add this information to where.py?
We need to create a new column in the ready data frame and put information about world justice in this country and this ranking place.
For example:
```
Finland, ......., 3/126
```
Thank you very much!

_Originally posted by @serhii73 in https://github.com/place2live/place2live/issues/33#issuecomment-546212784_

**Comment by dreamerchandra** [comment]
Hey @serhii73 I'll take this issue

**Comment by serhii73** [comment]
Thank you very much!

**Comment by dreamerchandra** [comment]
@serhii73  just started to work on it... I've got a doubt... 
Is there any script which aggregates (copies to) `world_justice.csv` to `countries.csv`?
Or is that a manual process?

**Comment by dreamerchandra** [comment]
hey @serhii73... just started with the project... I want to integrate `world_justice.csv` into `countries.csv` I could see `scraper` module is written for this job... But what's the starting point of it? How to run it?

**Comment by serhii73** [comment]
> just started with the project... I want to integrate world_justice.csv into countries.csv

No. Please read https://github.com/place2live/place2live/blob/master/world_justice_project/world_justice.csv this file with python and add to ready data frame and show it to a user.
That's it.
Thank you very much!

**Comment by dreamerchandra** [comment]
>this file with python and add to ready data frame and show it to a user.


@serhii73 is there any samples works already done... Please share the file URLs

**Comment by serhii73** [comment]
> > this file with python and add to ready data frame and show it to a user.
> 
> @serhii73 is there any samples works already done... Please share the file URLs

Sorry?
Can you tell me more please whats failing?

**Comment by dreamerchandra** [comment]
I can't understand what's meant by `ready data frame`... Could you share some reference in code what do you meant by that?

**Comment by serhii73** [comment]
Thank you very much for your question.
https://github.com/place2live/place2live/blob/master/where.py#L522 - `print_out_df` is ready data frame.
Does that make sense?

**Comment by dreamerchandra** [comment]
Thanks for clarifying... Yes, it does make sense but still, I've few doubts...
- [df](https://github.com/place2live/place2live/blob/master/where.py#L10) is being initialized from `countries.csv` and `justice data` is not in that CSV. To import data from `world_justice.csv` into `counties.csv` [I need to do this](https://github.com/place2live/place2live/issues/160#issuecomment-546588466). But your [reply](https://github.com/place2live/place2live/issues/160#issuecomment-546616728) says not to import data into `coutries.csv`
 - So I'm wondering is there any way to add data into `print_out_df` without even importing justice.csv into countries.csv. If so can you share me any reference work that has previously done, else clarify the way I need to proceed

**Comment by serhii73** [comment]
https://github.com/place2live/place2live/blob/master/where.py#L520 - this is an example of how to add a new column to the data frame.

**Comment by dreamerchandra** [comment]
thanks, I'll check
