### ISSUE TITLE
Missing bs4 library in requirements.txt

### ISSUE THREAD

**Issue by spineki** [serhii73/place2live#171]
**Describe the bug**
bs4 is not written in the requirements.txt file. It's a missing dependency.

**To Reproduce**
1) go to traffic_related_death_rate.py
2) it's written: from bs4 import Beautifulsoup

**Expected behavior**
impossible to run the file

**Desktop:**
 - OS: windows
 - windows 10

**Comment by hs2361** [comment]
Can I take this issue?
