### ISSUE TITLE
Add documentation to python files

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#2]
You need add documentation to `where.py`, `items.py`, `lists_of_cities.py`

**Comment by aredshaw** [comment]
I would like to make at attempt at this.

**Comment by aredshaw** [comment]
I see there could really be some documentation for steps for installation as well.

**Comment by serhii73** [comment]
Thank you very much!

**Comment by aredshaw** [comment]
Interesting. After setting up the environment and running where.py, I get this error message:
```
  File "where.py", line 16
    print(f"'{country}' is an invalid country. Please try again.")
                                                                ^
SyntaxError: invalid syntax
```

**Comment by aredshaw** [comment]
I was never prompted for a place.

**Comment by serhii73** [comment]
`python --version` - Please show the output this command.

**Comment by serhii73** [comment]
> I suppose I could still document how to install the dependencies though (on Linux at least).
Thank you very much @aredshaw

**Comment by aredshaw** [comment]
I'm using Python 2.7.16. Does it need to be Python 3 for this to work? I could try upgrading.

**Comment by aredshaw** [comment]
I made changes and uploaded them in the aredshaw branch. Is this how it is done? Can you checkout the changes and accept or reject them? I am a bit of a novice with the GitHub process.

**Comment by serhii73** [comment]
> I'm using Python 2.7.16. Does it need to be Python 3 for this to work? I could try upgrading.
> 
> I also have Python 3.6.8 installed, and after running `python3 where.py`, I got the same error message. I wonder if I am missing some other dependency?
> 
> Python 3.7.4 gave me the same error.

Can you please show all terminal output? Thank you.

**Comment by serhii73** [comment]
> I made changes and uploaded them in the aredshaw branch. Is this how it is done? Can you checkout the changes and accept or reject them? I am a bit of a novice with the GitHub process.

Don't worry. I will help you.

**Comment by aredshaw** [comment]
Oh, I see it has to do with pandas.
```
Traceback (most recent call last):
  File "where.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by serhii73** [comment]
1. Install [Python 3.7](https://www.python.org/)
2. [Create and activate the virtual environment](https://docs.python.org/3.7/library/venv.html)
3. Install requirements for the project: `pip install -r requirements.txt`
4. `python where.py`

Aaron, I think the script will be work only with Python 3.7 or 3.6

**Comment by serhii73** [comment]
Please, try it 
```
python3 -m venv env
```
Then `source env/bin/activate`
Then `pip install -r requirements.txt` and `python where.py`

**Comment by serhii73** [comment]
> I made changes and uploaded them in the aredshaw branch. Is this how it is done? Can you checkout the changes and accept or reject them? I am a bit of a novice with the GitHub process.

https://guides.github.com/activities/forking/
I think it will be useful for you.
1. Fork
2. Clone
3. create a branch
4. Add a code
5. git commit and push

**Comment by aredshaw** [comment]
I tried the above commands, and now it works. Do you want me to put those instructions in the docs, for if they run into a problem?

**Comment by serhii73** [comment]
@aredshaw It will b amazing.
Thank you very much, Aaron.

**Comment by aredshaw** [comment]
I keep trying, but the build keeps failing. I've committed the changes.

**Comment by serhii73** [comment]
Don't worry. I will fix the Travis CI.

**Comment by serhii73** [comment]
Thank you very much!
