### ISSUE TITLE
Scrape `List of countries by number of military and paramilitary personnel`

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#20]
Scrape https://en.wikipedia.org/wiki/List_of_countries_by_number_of_military_and_paramilitary_personnel

**Comment by ItsLaro** [comment]
Can I be assigned to do this? 😀

**Comment by gunjanraval** [comment]
In which format do you want the output?

**Comment by serhii73** [comment]
Hello @gunjanraval How are you?
`Country` and `Per 1000 capita (active)`, `Per 1000 capita (total)` columns.
Thank you very much.

**Comment by gunjanraval** [comment]
Hey! I've scraped it and saved it in a .csv file! Where do you want me to save it?

**Comment by serhii73** [comment]
you can create a folder `military` and put a script and CSV there. Ok?
Thank you very much!

**Comment by gunjanraval** [comment]
Done!

**Comment by gunjanraval** [comment]
All errors have been fixed!
