### ISSUE TITLE
Add rating range

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#38]
Add rating range to `where.py`
Add the smallest and largest score for each rating.

**Comment by nikitaden03** [comment]
Need to output the maximum and minimum values ​​at the end or when the user enters the data?

**Comment by serhii73** [comment]
Hello @nikitaden03 
Please, look:
```
$ python where.py
What is your country? Germany
In your country purchasing power index is 115.98
What is your purchasing power index (higher is better)? 
```
I got a few letters where people tell me what they don't understand the range of score.
```
What is your purchasing power index (higher is better)? 
```
(`What is your desirable purchasing power index?` will be better, need to change the question in future)
A user will write `purchasing power index`, ok, but user doesn't understand what the worst score in the world and what the best score in the world.
If `output` will be like:
```
In your country purchasing power index is 115.98, the best score in the world is 200(name of a country, for example, Japan), the worst is 2(name of a country too)
```
(`In your country purchasing power index is` - also better will be to replace `your country` wite country what user wrote)
