### ISSUE TITLE
Add additional information about countries

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#4]
Add information to `where.py` if countries are coincident - show additional information. This information you can see at the screenshot.

**Comment by serhii73** [comment]
![Screenshot from 2019-05-29 21-51-36](https://user-images.githubusercontent.com/24910277/58614137-3d94bb80-82c0-11e9-9971-dc149b11dfaa.png)

**Comment by Fyrebright** [comment]
I'm looking to contribute, but I am unsure exactly what information you are wanting to be added.

**Comment by serhii73** [comment]
Hi :)
You run a script that will find countries.
If among these countries there are those who are good with migrants, you can show it.
Thank you.
