### ISSUE TITLE
Add Ukrainian language to where.py

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#41]
Додати українську мову до `where.py`, питати українською або англiйською.

**Comment by undef1nd** [comment]
@serhii73 Привіт! Тобто Ви хочете дати можливість вибрати мову? Я правильно зрозуміла?

**Comment by serhii73** [comment]
Так, є люди, які не є інженерами, та не дуже знають англійську, якщо `python where.py` вони зробити можуть, то далі в них виникають складності, щодо розуміння, що від них хочуть.
І мене просили, що було б дуже класно, якщо б я добавив українську мову.

**Comment by undef1nd** [comment]
@serhii73 Дякую за пояснення! Я би взялася за це. Заодно по ходу розберуся в коді цієі репи 🙂

**Comment by serhii73** [comment]
Дякую!

**Comment by serhii73** [comment]
@undef1nd можливо простіше створити навіть окремий скрипт...
але, два окремих скрипта тоді прийдеться підтримувати. краще придумати, як це зробити у існуючому `where.py`

**Comment by undef1nd** [comment]
@serhii73 Я подумаю на тижні і ближче до вихідних напишу Вам, що придумала. Щоб погодити підхід 🙂
